import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{createClient}from'@supabase/supabase-js';
import'./style.css';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'';
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'';
const supabase=SUPABASE_URL&&SUPABASE_KEY?createClient(SUPABASE_URL,SUPABASE_KEY):null;
const demoCourses=[
{id:'c1',title:'پایتون از صفر تا پروژه',description:'پایتون را با تمرین‌های واقعی و پروژه‌های مرحله‌ای یاد بگیر.',category:'programming',level:'beginner',price:890000},
{id:'c2',title:'آردوینو و ساخت ربات مسیر‌یاب',description:'از مدار و سنسور تا کدنویسی یک ربات کامل.',category:'robotics',level:'beginner',price:1190000},
{id:'c3',title:'ESP32 و اینترنت اشیا',description:'پروژه‌های هوشمند با Wi‑Fi، سنسور و داشبورد وب.',category:'robotics',level:'intermediate',price:1490000},
{id:'c4',title:'طراحی سایت مدرن',description:'HTML، CSS و JavaScript برای ساخت سایت‌های حرفه‌ای.',category:'web',level:'beginner',price:990000}
];
const money=n=>Number(n||0).toLocaleString('fa-IR')+' تومان';
const catName=c=>({robotics:'رباتیک',programming:'برنامه‌نویسی',web:'طراحی سایت'}[c]||c);

function App(){
 const[page,setPage]=useState('home'),[courses,setCourses]=useState(demoCourses),[session,setSession]=useState(null),[profile,setProfile]=useState(null),[assistantOpen,setAssistantOpen]=useState(false);
 const nav=p=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})};
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
 useEffect(()=>{if(!session){setProfile(null);return}supabase.from('profiles').select('*').eq('id',session.user.id).maybeSingle().then(({data})=>setProfile(data))},[session]);
 useEffect(()=>{if(!supabase)return;supabase.from('courses').select('*').eq('published',true).order('featured',{ascending:false}).then(({data})=>{if(data?.length)setCourses(data)})},[]);
 return <div className="app">
  <header className="header"><div className="navWrap"><button className="brand" onClick={()=>nav('home')}><span className="brandMark">R</span><span><b>رازی‌تک</b><small>ACADEMY</small></span></button><nav className="desktopNav">{[['home','خانه'],['courses','دوره‌ها'],['robotics','آزمایشگاه'],['about','درباره ما']].map(([p,t])=><button className={page===p?'active':''} key={p} onClick={()=>nav(p)}>{t}</button>)}</nav><div className="navActions">{session?<button className="profileBtn" onClick={()=>nav('dashboard')}>◉ {profile?.full_name||'حساب من'}</button>:<button className="primary mini" onClick={()=>nav('auth')}>ورود / ثبت‌نام</button>}</div></div><div className="mobileNav">{[['home','⌂','خانه'],['courses','▣','دوره‌ها'],['robotics','🤖','آزمایشگاه'],['dashboard','◉','حساب']].map(([p,i,t])=><button className={page===p?'active':''} onClick={()=>nav(p)} key={p}><span>{i}</span>{t}</button>)}</div></header>
  <main>{page==='home'&&<Home nav={nav} courses={courses} openAssistant={()=>setAssistantOpen(true)}/>} {page==='courses'&&<Courses courses={courses} nav={nav} session={session}/>} {page==='auth'&&<Auth nav={nav} setSession={setSession}/>} {page==='dashboard'&&<Dashboard session={session} profile={profile} nav={nav} courses={courses}/>} {page==='robotics'&&<Robotics/>} {page==='about'&&<About nav={nav}/>}</main>
  <footer><div className="footerGrid"><div><div className="footerBrand">رازی‌تک</div><p>آموزش پروژه‌محور در برنامه‌نویسی، رباتیک و الکترونیک.</p></div><div><b>دسترسی سریع</b><button onClick={()=>nav('courses')}>دوره‌ها</button><button onClick={()=>nav('robotics')}>آزمایشگاه</button></div><div><b>رازی‌تک</b><span>پروژه‌های واقعی</span><span>پشتیبانی آموزشی</span></div><div><b>ارتباط</b><span>پشتیبانی آنلاین</span><span>شنبه تا پنجشنبه</span><span>طراحی و توسعه: امیرعلی رضی خادمی</span></div></div><div className="footerBottom"><span>© ۱۴۰۵ رازی‌تک — تمامی حقوق محفوظ است.</span><span>امنیت و حریم خصوصی</span></div></footer>
  <button className="assistantFab" onClick={()=>setAssistantOpen(true)}>✦<span>دستیار هوشمند</span></button>{assistantOpen&&<Assistant close={()=>setAssistantOpen(false)}/>}
 </div>
}

function Home({nav,courses,openAssistant}){return <>
 <section className="hero"><div className="heroGlow"/><div className="heroCopy"><span className="eyebrow">RAZITECH ACADEMY • ۱۴۰۵</span><h1>ایده‌ات را<br/><em>به پروژه تبدیل کن.</em></h1><p>آموزش پروژه‌محور و یک مسیر یادگیری واقعی؛ از اولین خط کد تا ساخت پروژه.</p><div className="heroActions"><button className="primary" onClick={()=>nav('courses')}>شروع یادگیری <b>←</b></button><button className="ghost" onClick={()=>nav('robotics')}>ورود به آزمایشگاه</button></div><div className="heroStats"><span><b>۴+</b> مسیر آموزشی</span><span><b>∞</b> پروژه عملی</span><span><b>۲۴/۷</b> دستیار هوشمند</span></div></div><div className="heroVisual"><div className="orbital"><div className="orbit o1"/><div className="orbit o2"/><div className="core">R</div><span className="float f1">⚡</span><span className="float f2">🤖</span><span className="float f3">⌘</span></div><div className="visualCard"><span>SMART LAB</span><b>Build. Test. Learn.</b><button onClick={openAssistant}>گفت‌وگو با دستیار ↗</button></div></div></section>
 <section className="paths section"><div className="sectionTitle"><span className="eyebrow">WHERE TO START?</span><h2>مسیر خودت را انتخاب کن.</h2><p>از جایی شروع کن که به پروژه‌ات نزدیک‌تر است.</p></div><div className="pathGrid"><button onClick={()=>nav('courses')}><span>⌘</span><b>برنامه‌نویسی</b><small>Python • Web • JavaScript</small><i>شروع مسیر ←</i></button><button onClick={()=>nav('robotics')}><span>🤖</span><b>رباتیک</b><small>Arduino • ESP32 • Sensors</small><i>ورود به آزمایشگاه ←</i></button><button onClick={()=>nav('courses')}><span>⚙</span><b>ساخت پروژه</b><small>یادگیری و اجرای پروژه</small><i>شروع یادگیری ←</i></button></div></section>
 <section className="section"><div className="sectionTitle row"><div><span className="eyebrow">LEARNING</span><h2>دوره‌های منتخب</h2></div><button className="textBtn" onClick={()=>nav('courses')}>همه دوره‌ها ←</button></div><div className="courseGrid">{courses.slice(0,4).map(c=><CourseCard key={c.id} c={c} nav={nav}/>)}</div></section>
 <section className="smartBanner"><div><span className="eyebrow">SMART ASSISTANT</span><h2>وقتی گیر کردی، تنها نیستی.</h2><p>برای انتخاب مسیر، رفع خطا، توضیح مفاهیم و ایده‌پردازی از دستیار رازی‌تک کمک بگیر.</p><button className="primary" onClick={openAssistant}>از دستیار بپرس ✦</button></div><div className="chatMock"><div className="chatHead"><span className="dot"/> دستیار رازی‌تک</div><div className="bubble">سلام! 👋 پروژه‌ات را بگو تا قدم‌به‌قدم جلو برویم.</div><div className="suggestions"><span>🤖 ساخت ربات</span><span>💻 انتخاب دوره</span><span>🧠 رفع خطا</span></div></div></section>
 </>}
function CourseCard({c,nav}){return <article className="courseCard"><div className="courseArt"><span>{c.category==='robotics'?'🤖':c.category==='web'?'◫':'⌘'}</span><small>{catName(c.category)}</small></div><div className="cardBody"><div className="meta"><span>{c.level==='beginner'?'مقدماتی':'متوسط'}</span><span>پروژه‌محور</span></div><h3>{c.title}</h3><p>{c.description}</p><div className="cardFoot"><strong>{money(c.price)}</strong><button onClick={()=>nav('courses')}>جزئیات ↗</button></div></div></article>}
function Courses({courses,nav,session}){return <section className="page"><PageHero eyebrow="LEARNING HUB" title="یادگیری که به پروژه ختم می‌شود." text="دوره‌های پروژه‌محور را انتخاب کن، بساز و نتیجه را ببین."/><div className="filterLine"><span>{courses.length} دوره آموزشی</span><button className="filterActive">همه مسیرها</button><button>برنامه‌نویسی</button><button>رباتیک</button></div><div className="courseGrid large">{courses.map(c=><CourseCard key={c.id} c={c} nav={nav}/>)}</div>{!session&&<div className="callout"><b>برای ذخیره پیشرفت وارد حساب شو.</b><button className="primary mini" onClick={()=>nav('auth')}>ساخت حساب رایگان</button></div>}</section>}
function Auth({nav,setSession}){const[mode,setMode]=useState('login'),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[name,setName]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');if(!supabase){setError('Supabase هنوز در محیط اجرا تنظیم نشده است.');return}setLoading(true);const r=mode==='login'?await supabase.auth.signInWithPassword({email,password:pass}):await supabase.auth.signUp({email,password:pass,options:{data:{full_name:name}}});setLoading(false);if(r.error){setError(r.error.message.includes('Invalid login')?'ایمیل یا رمز عبور نادرست است.':r.error.message);return}setSession(r.data.session);if(mode==='register'&&!r.data.session)setError('ثبت‌نام انجام شد؛ ایمیل تأیید را بررسی کن.');else nav('dashboard')};return <section className="authPage"><div className="authVisual"><span className="eyebrow">RAZITECH ID</span><h1>یک حساب.<br/><em>تمام پروژه‌ها.</em></h1><p>پیشرفت دوره‌ها و مسیر یادگیری‌ات را یک‌جا مدیریت کن.</p><div className="authBullets"><span>✓ ذخیره پیشرفت</span><span>✓ مسیر یادگیری شخصی</span><span>✓ دستیار هوشمند</span></div></div><div className="authCard"><div className="tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>ورود</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>ثبت‌نام</button></div><h2>{mode==='login'?'خوش برگشتی 👋':'حساب جدید بساز'}</h2><p>{mode==='login'?'وارد فضای شخصی رازی‌تک شو.':'رایگان شروع کن و مسیرت را ذخیره کن.'}</p><form onSubmit={submit}>{mode==='register'&&<label>نام و نام خانوادگی<input value={name} onChange={e=>setName(e.target.value)} required/></label>}<label>ایمیل<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>رمز عبور<input type="password" value={pass} onChange={e=>setPass(e.target.value)} minLength="6" required/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={loading}>{loading?'در حال بررسی...':mode==='login'?'ورود به حساب':'ساخت حساب رایگان'}</button></form><small>با ادامه، شرایط استفاده و حریم خصوصی را می‌پذیرید.</small></div></section>}
function Dashboard({session,profile,nav,courses}){if(!session)return <div className="empty page"><h2>ابتدا وارد حساب شوید.</h2><button className="primary" onClick={()=>nav('auth')}>ورود / ثبت‌نام</button></div>;return <section className="page dashboard"><div className="dashTop"><div><span className="eyebrow">MY RAZITECH</span><h1>سلام، {profile?.full_name||'دوست فناوری'} 👋</h1><p>آماده‌ای پروژه بعدی را بسازیم؟</p></div><button className="ghost" onClick={()=>supabase?.auth.signOut()}>خروج</button></div><div className="dashStats"><div><span>دوره‌ها</span><b>{courses.length.toLocaleString('fa-IR')}</b></div><div><span>پروژه‌ها</span><b>∞</b></div><div><span>آزمایشگاه</span><b>✓</b></div></div><div className="dashGrid"><div className="panel"><div className="panelTitle"><h2>مسیرهای یادگیری</h2><button onClick={()=>nav('courses')}>مشاهده همه</button></div>{courses.slice(0,3).map(c=><div className="learningRow" key={c.id}><span>{c.category==='robotics'?'🤖':'⌘'}</span><div><b>{c.title}</b><small>آماده شروع • پروژه‌محور</small></div><button>ادامه ←</button></div>)}</div><div className="panel"><div className="panelTitle"><h2>دسترسی سریع</h2><button onClick={()=>nav('robotics')}>آزمایشگاه</button></div><div className="miniEmpty">دوره‌ای را انتخاب کن و ساخت پروژه را شروع کن.</div></div></div></section>}
function Robotics(){const cards=[['🤖','مسیر‌یاب آردوینو','سنسور + موتور + الگوریتم حرکت'],['📡','ESP32 و IoT','اتصال سخت‌افزار به وب و شبکه'],['🧠','ربات هوشمند','ترکیب کنترل، سنسور و منطق']];return <section className="page"><PageHero eyebrow="ROBOTICS LAB" title="آزمایشگاه ساخت." text="اینجا یادگیری فقط خواندن نیست؛ می‌سازیم، تست می‌کنیم و بهترش می‌کنیم."/><div className="labGrid">{cards.map(([i,t,s])=><article key={t}><span>{i}</span><b>{t}</b><p>{s}</p><button>مشاهده مسیر ←</button></article>)}</div><div className="labSteps"><span>01<br/><b>ایده</b></span><span>02<br/><b>مدار</b></span><span>03<br/><b>کد</b></span><span>04<br/><b>تست</b></span><span>05<br/><b>پروژه</b></span></div></section>}
function About({nav}){return <section className="page"><PageHero eyebrow="ABOUT RAZITECH" title="فناوری را باید ساخت." text="رازی‌تک یک فضای آموزشی و ساخت‌محور برای برنامه‌نویسی، رباتیک و الکترونیک است."/><div className="aboutGrid"><div><span className="eyebrow">OUR MISSION</span><h2>از یادگیری تئوری تا تجربه واقعی.</h2><p>مسیرهای آموزشی را با پروژه و آزمایش ترکیب می‌کنیم تا یادگیری به چیزی تبدیل شود که بتوانی نشانش بدهی.</p><button className="primary" onClick={()=>nav('courses')}>شروع یادگیری</button></div><div className="quote">«هر پروژه، یک سؤال جدید است؛ و هر سؤال، شروع یک ساختن.»<small>— رازی‌تک</small></div></div></section>}
function PageHero({eyebrow,title,text}){return <div className="pageHero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Assistant({close}){const[q,setQ]=useState(''),[messages,setMessages]=useState([{from:'bot',text:'سلام! 👋 من دستیار رازی‌تک هستم. درباره دوره، رباتیک یا پروژه‌ات بپرس.'}]);const send=e=>{e?.preventDefault();if(!q.trim())return;const x=q.trim();setMessages(m=>[...m,{from:'user',text:x},{from:'bot',text:x.includes('ربات')?'برای رباتیک، مسیر Arduino → سنسورها → کنترل موتور را پیشنهاد می‌کنم.':x.includes('دوره')?'اگر تازه شروع می‌کنی، پایتون یا آردوینو مسیرهای مناسبی برای شروع پروژه‌محور هستند.':'سؤال خوبی است! هدف پروژه و ابزارهایی که داری را بگو تا مرحله بعدی را مشخص کنیم.'}]);setQ('')};return <div className="assistantOverlay" onClick={close}><div className="assistant" onClick={e=>e.stopPropagation()}><div className="assistantHeader"><div><span className="dot"/> دستیار رازی‌تک</div><button onClick={close}>×</button></div><div className="messages">{messages.map((m,i)=><div className={m.from} key={i}>{m.text}</div>)}</div><form onSubmit={send}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="سؤالت را بنویس..."/><button>↑</button></form></div></div>}

createRoot(document.getElementById('root')).render(<App/>);